// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-ZOL0PzBbi4Gp8zP-XQI44lFPYDlPGA',
    appId: '1:588971140833:web:fa136ca76ea1f274d4f9a0',
    messagingSenderId: '588971140833',
    projectId: 'chatbox-e43ad',
    authDomain: 'chatbox-e43ad.firebaseapp.com',
    storageBucket: 'chatbox-e43ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPeDZbpGL_-wLHwJMdPWfH0SAvJGNWUiM',
    appId: '1:588971140833:android:6a0ac87bbb9b8f15d4f9a0',
    messagingSenderId: '588971140833',
    projectId: 'chatbox-e43ad',
    storageBucket: 'chatbox-e43ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRp10ell77SSPiLdFk_YRd90Vqe7c0--c',
    appId: '1:588971140833:ios:2ce0427c902695f2d4f9a0',
    messagingSenderId: '588971140833',
    projectId: 'chatbox-e43ad',
    storageBucket: 'chatbox-e43ad.firebasestorage.app',
    iosBundleId: 'com.example.chatboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRp10ell77SSPiLdFk_YRd90Vqe7c0--c',
    appId: '1:588971140833:ios:2ce0427c902695f2d4f9a0',
    messagingSenderId: '588971140833',
    projectId: 'chatbox-e43ad',
    storageBucket: 'chatbox-e43ad.firebasestorage.app',
    iosBundleId: 'com.example.chatboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2-ZOL0PzBbi4Gp8zP-XQI44lFPYDlPGA',
    appId: '1:588971140833:web:c0ca236f467b4fd9d4f9a0',
    messagingSenderId: '588971140833',
    projectId: 'chatbox-e43ad',
    authDomain: 'chatbox-e43ad.firebaseapp.com',
    storageBucket: 'chatbox-e43ad.firebasestorage.app',
  );
}
